Write-Host "=== create_mof.ps1 starting ==="

# -----------------------------------------------------------------------
# Ensure all module paths are in PSModulePath before DSC compilation
# -----------------------------------------------------------------------
# DSC MOF compilation spawns an isolated runspace that inherits $env:PSModulePath.
# All three paths must be present or Import-DscResource will fail at compile time.
$requiredPaths = @(
    "C:\Program Files\WindowsPowerShell\Modules",
    "C:\Windows\system32\WindowsPowerShell\v1.0\Modules",
    "C:\Program Files (x86)\WindowsPowerShell\Modules"
)
foreach ($p in $requiredPaths) {
    if ($p -and ($env:PSModulePath -split ';') -notcontains $p) {
        Write-Host "Adding to PSModulePath: $p"
        $env:PSModulePath = "$p;$env:PSModulePath"
    }
}

Import-Module PowerSTIG -Force

# -----------------------------------------------------------------------
# Resolve all paths from $PSScriptRoot
# -----------------------------------------------------------------------
$HardeningDir = $PSScriptRoot
$OutputPath   = Join-Path $HardeningDir "MOF"
$OrgSettings  = Join-Path $HardeningDir "WindowsServer-2022-MS-2.1.org.pamdata.xml"

Write-Host "Hardening directory : $HardeningDir"
Write-Host "MOF output path     : $OutputPath"
Write-Host "Org settings file   : $OrgSettings"
Write-Host "PSModulePath        : $env:PSModulePath"

# Create MOF output folder if it does not exist
if (!(Test-Path $OutputPath)) {
    New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null
    Write-Host "Created MOF output directory."
}

# Validate the org settings XML was generated by install_dsc_deps.ps1
if (!(Test-Path $OrgSettings)) {
    Write-Error "Org settings XML not found: $OrgSettings"
    Write-Error "Ensure install_dsc_deps.ps1 completed successfully."
    exit 1
}

# Log the full XML for debug visibility in Packer output
Write-Host "--- Org settings XML contents:"
Get-Content $OrgSettings | ForEach-Object { Write-Host "  $_" }

# Pre-flight: verify DSC resource is resolvable before attempting compilation
Write-Host "--- Verifying DSC resources..."
try {
    $dscCheck = Get-DscResource -Name WindowsServer -Module PowerSTIG -ErrorAction Stop
    Write-Host "DSC resource confirmed: $($dscCheck.Name) from $($dscCheck.Module)"
} catch {
    Write-Error "WindowsServer DSC resource not found: $_"
    exit 1
}

# -----------------------------------------------------------------------
# DSC Configuration block
# -----------------------------------------------------------------------
Configuration ApplyWindowsServerStig {
    param (
        [string]$NodeName = 'localhost'
    )

    Import-DscResource -ModuleName PowerSTIG

    Node $NodeName {
        WindowsServer 'ConfigureServer' {

            OsVersion = '2022'
            OsRole    = 'MS'

            # OrgSettings XML auto-generated from PowerSTIG module's .org.default.xml
            # by install_dsc_deps.ps1 — always complete for the installed version
            OrgSettings = $OrgSettings

            Exception = @{
                # Allow local accounts RDP access (Guests removed from deny list)
                'V-254439' = @{ 'Identity' = 'Guests' }

                # Allow Admin accounts RDP access (Guests removed from deny list)
                'V-254435' = @{ 'Identity' = 'Guests' }

                # Allow any logged-in user to shut down — enhances GCP cost savings.
                # 'Everyone' used because PowerSTIG doesn't format multi-value correctly.
                'V-254501' = @{ 'Identity' = 'Everyone' }

                # Password exceptions — GCP/IAP handles auth externally,
                # no direct local password access is permitted by GCP networking.
                'V-254446' = @{ 'ValueData'  = '0' }        # Allow blank password
                'V-254289' = @{ 'PolicyValue' = '0' }        # Permit blank password (policy)
                'V-254290' = @{ 'PolicyValue' = '0' }        # Disable min password age
                'V-254291' = @{ 'PolicyValue' = '0' }        # Allow blank password (policy)
                'V-254292' = @{ 'PolicyValue' = 'Disabled' } # Disable complexity requirement
            }

            SkipRule = @(
                'V-254254.c',  # Known PowerSTIG bug — https://github.com/microsoft/PowerStig/issues/1360
                'V-254271'     # PNRP feature absent on Server 2022/2025
            )
        }
    }
}

# -----------------------------------------------------------------------
# Compile
# -----------------------------------------------------------------------
Write-Host "=== Generating MOF..."
ApplyWindowsServerStig -OutputPath $OutputPath

$mofFile = Join-Path $OutputPath "localhost.mof"
if (!(Test-Path $mofFile)) {
    Write-Error "MOF file was not generated at: $mofFile"
    exit 1
}
Write-Host "MOF generated: $mofFile"
