$requiredPaths = @(
    "C:\Program Files\WindowsPowerShell\Modules",           # AllUsers install location
    "C:\Windows\system32\WindowsPowerShell\v1.0\Modules",  # DSC LCM system path
    "C:\Program Files (x86)\WindowsPowerShell\Modules"     # 32-bit fallback
)
foreach ($p in $requiredPaths) {
    if ($p -and ($env:PSModulePath -split ';') -notcontains $p) {
        Write-Host "Adding to PSModulePath: $p"
        $env:PSModulePath = "$p;$env:PSModulePath"
    }
}

Import-Module PowerSTIG -Force

# -----------------------------------------------------------------------
# Resolve paths from $PSScriptRoot (= CloudBuild _HARDENING_TARGET_DIR)
# -----------------------------------------------------------------------
$HardeningDir = $PSScriptRoot
$OutputPath   = Join-Path $HardeningDir "MOF"
$OrgSettings  = Join-Path $HardeningDir "WindowsServer-2022-MS-2.1.org.pamdata.xml"

Write-Host "Hardening directory : $HardeningDir"
Write-Host "MOF output path     : $OutputPath"
Write-Host "Org settings file   : $OrgSettings"
Write-Host "PSModulePath        : $env:PSModulePath"

# Create the MOF output folder if it does not already exist
if (!(Test-Path $OutputPath)) {
    New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null
    Write-Host "Created MOF output directory."
}

# Validate that the org settings XML was generated by install_dsc_deps.ps1
if (!(Test-Path $OrgSettings)) {
    Write-Error "Org settings XML not found: $OrgSettings"
    Write-Error "Ensure install_dsc_deps.ps1 ran successfully before this script."
    exit 1
}

# Pre-flight: confirm the WindowsServer DSC resource is resolvable
Write-Host "Verifying DSC resources are available..."
try {
    $dscCheck = Get-DscResource -Name WindowsServer -Module PowerSTIG -ErrorAction Stop
    Write-Host "DSC resource confirmed: $($dscCheck.Name) from $($dscCheck.Module)"
} catch {
    Write-Error "WindowsServer DSC resource not found. Error: $_"
    exit 1
}

# -----------------------------------------------------------------------
# DSC Configuration block
# -----------------------------------------------------------------------
Configuration ApplyWindowsServerStig {
    param (
        [string]$NodeName = 'localhost'   # Target node; 'localhost' applies to this machine
    )

    # Import the PowerSTIG DSC composite resource within the configuration context
    Import-DscResource -ModuleName PowerSTIG

    Node $NodeName {
        WindowsServer 'ConfigureServer' {

            OsVersion = '2022'    # Target OS version
            OsRole    = 'MS'      # MS = Member Server (not DC = Domain Controller)

            # StigVersion omitted — auto-selects latest available version.
            # Version 2.1 was removed from PowerSTIG as of 3/3/25.

            # Org settings XML auto-generated by install_dsc_deps.ps1 from the
            # PowerSTIG module's .org.default.xml + PAM overrides
            OrgSettings = $OrgSettings

            # Exceptions override STIG rules that would break GCP/IAP remote access
            # workflows or cost-saving features in this environment.
            Exception = @{

                # --- Remote Desktop Access Exceptions ---
                # Allow local accounts (Guests removed from deny list) to use RDP
                'V-254439' = @{ 'Identity' = 'Guests' }

                # Allow Admin accounts (Guests removed from deny list) to connect via RDP
                'V-254435' = @{ 'Identity' = 'Guests' }

                # --- Shutdown Rights Exception ---
                # Allow any logged-in user to shut down — enhances cost savings.
                # 'Everyone' used because PowerSTIG does not correctly format multi-value
                # responses for this rule (e.g., Administrators + Local).
                'V-254501' = @{ 'Identity' = 'Everyone' }

                # --- Password Policy Exceptions ---
                # Waived: GCP/IAP handles authentication externally.
                # No direct local password access is permitted by GCP networking.

                # Allow blank passwords
                'V-254446' = @{ 'ValueData' = '0' }

                # Permit use of blank passwords at policy level
                'V-254289' = @{ 'PolicyValue' = '0' }

                # Disable minimum password age — allows pam_admin password rotation on demand
                'V-254290' = @{ 'PolicyValue' = '0' }

                # Allow blank password at policy level
                'V-254291' = @{ 'PolicyValue' = '0' }

                # Disable password complexity (GCP handles auth)
                'V-254292' = @{ 'PolicyValue' = 'Disabled' }
            }

            # Rules skipped due to known bugs or absent features in this environment
            SkipRule = @(
                'V-254254.c',  # Known PowerSTIG bug — https://github.com/microsoft/PowerStig/issues/1360
                'V-254271'     # PNRP feature not present on Server 2022/2025
            )
        }
    }
}

# -----------------------------------------------------------------------
# Compile and apply
# -----------------------------------------------------------------------
Write-Host "Generating MOF..."
ApplyWindowsServerStig -OutputPath $OutputPath

# Confirm MOF was actually created
$mofFile = Join-Path $OutputPath "localhost.mof"
if (!(Test-Path $mofFile)) {
    Write-Error "MOF file was not generated at: $mofFile"
    exit 1
}
Write-Host "MOF generated successfully: $mofFile"

# Apply the MOF — enforce all STIG settings on this machine
# -Wait    : Synchronous (block until complete)
# -Verbose : Stream progress to console
# -Force   : Apply even if a DSC job is already running
