# create_mof.ps1
# Compiles a DSC MOF and applies it via Start-DscConfiguration.
#
# KEY FIX — "Unexpected token '$OutputPath'":
#   Variables defined in script scope are NOT accessible inside a DSC Configuration
#   block — the Configuration block compiles in an isolated context. The fix is to
#   pass $OrgSettings as an explicit parameter into the Configuration function,
#   and call the configuration function with named arguments after defining it.
#
# All paths derived from $PSScriptRoot = CloudBuild _HARDENING_TARGET_DIR
# Must be run as Administrator after install_PowerSTIG.ps1 and install_dsc_deps.ps1.

Write-Host "=== create_mof.ps1 starting ==="

# -----------------------------------------------------------------------
# Ensure all module paths are in PSModulePath before DSC compilation
# -----------------------------------------------------------------------
$requiredPaths = @(
    "C:\Program Files\WindowsPowerShell\Modules",
    "C:\Windows\system32\WindowsPowerShell\v1.0\Modules",
    "C:\Program Files (x86)\WindowsPowerShell\Modules"
)
foreach ($p in $requiredPaths) {
    if ($p -and ($env:PSModulePath -split ';') -notcontains $p) {
        Write-Host "Adding to PSModulePath: $p"
        $env:PSModulePath = "$p;$env:PSModulePath"
    }
}

Import-Module PowerSTIG -Force

# -----------------------------------------------------------------------
# Resolve paths — all from $PSScriptRoot
# -----------------------------------------------------------------------
$HardeningDir = $PSScriptRoot
$OutputPath   = Join-Path $HardeningDir "MOF"
$OrgSettings  = Join-Path $HardeningDir "WindowsServer-2022-MS-2.1.org.pamdata.xml"

Write-Host "Hardening directory : $HardeningDir"
Write-Host "MOF output path     : $OutputPath"
Write-Host "Org settings file   : $OrgSettings"
Write-Host "PSModulePath        : $env:PSModulePath"

# Create MOF output folder if it does not exist
if (!(Test-Path $OutputPath)) {
    New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null
    Write-Host "Created MOF output directory."
}

# Validate the org settings XML was generated by install_dsc_deps.ps1
if (!(Test-Path $OrgSettings)) {
    Write-Error "Org settings XML not found at: $OrgSettings"
    Write-Error "Ensure install_dsc_deps.ps1 completed successfully before running this script."
    exit 1
}

# Pre-flight: verify DSC resource is resolvable
Write-Host "--- Verifying DSC resources..."
try {
    $dscCheck = Get-DscResource -Name WindowsServer -Module PowerSTIG -ErrorAction Stop
    Write-Host "DSC resource confirmed: $($dscCheck.Name) from $($dscCheck.Module)"
} catch {
    Write-Error "WindowsServer DSC resource not found: $_"
    exit 1
}

# -----------------------------------------------------------------------
# DSC Configuration block
#
# IMPORTANT: $OrgSettings cannot be referenced directly from script scope
# inside a Configuration block — it must be declared as a parameter and
# passed explicitly when the configuration is called (see bottom of file).
# -----------------------------------------------------------------------
Configuration ApplyWindowsServerStig {
    param (
        [string]$NodeName   = 'localhost',
        [string]$OrgSettingsPath = ''      # Receives $OrgSettings from script scope below
    )

    Import-DscResource -ModuleName PowerSTIG

    Node $NodeName {
        WindowsServer 'ConfigureServer' {

            OsVersion   = '2022'
            OsRole      = 'MS'

            # Org settings path passed in as parameter — not referenced from script scope
            OrgSettings = $OrgSettingsPath

            Exception = @{
                # Allow local accounts RDP access (Guests removed from deny list)
                'V-254439' = @{ 'Identity' = 'Guests' }

                # Allow Admin accounts RDP access (Guests removed from deny list)
                'V-254435' = @{ 'Identity' = 'Guests' }

                # Allow any logged-in user to shut down — enhances GCP cost savings.
                # 'Everyone' used because PowerSTIG doesn't format multi-value correctly.
                'V-254501' = @{ 'Identity' = 'Everyone' }

                # Password exceptions — GCP/IAP handles auth externally
                'V-254446' = @{ 'ValueData'   = '0' }         # Allow blank password
                'V-254289' = @{ 'PolicyValue' = '0' }          # Permit blank password (policy)
                'V-254290' = @{ 'PolicyValue' = '0' }          # Disable min password age
                'V-254291' = @{ 'PolicyValue' = '0' }          # Allow blank password (policy)
                'V-254292' = @{ 'PolicyValue' = 'Disabled' }   # Disable complexity
            }

            SkipRule = @(
                'V-254254.c',   # Known PowerSTIG bug — https://github.com/microsoft/PowerStig/issues/1360
                'V-254271'      # PNRP feature absent on Server 2022/2025
            )
        }
    }
}

# -----------------------------------------------------------------------
# Compile — pass $OrgSettings explicitly as -OrgSettingsPath parameter
# -----------------------------------------------------------------------
Write-Host "=== Generating MOF..."
ApplyWindowsServerStig -OutputPath $OutputPath -OrgSettingsPath $OrgSettings

$mofFile = Join-Path $OutputPath "localhost.mof"
if (!(Test-Path $mofFile)) {
    Write-Error "MOF file was not generated at: $mofFile"
    exit 1
}
Write-Host "MOF generated: $mofFile"

# -----------------------------------------------------------------------
# Apply
# -----------------------------------------------------------------------

