steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/image-builders/windows-packer-builder:latest'
      - '-f'
      - 'win2022-oracle-client-dev/packer/scripts/Dockerfile'
      - '.'
images:
  - 'us-east4-docker.pkg.dev/$PROJECT_ID/image-builders/windows-packer-builder:latest'

# Replace with your service account email
serviceAccount: 'projects/ggn-nmfs-winde-dev-1/serviceAccounts/images-build-sa1@ggn-nmfs-winde-dev-1.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
