steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/packer-images/windows-packer-builder:latest'
      - '-f'
      - 'win2022-oracle-client-dev/packer/scripts/Dockerfile'
      - '.'
images:
  - 'us-east4-docker.pkg.dev/$PROJECT_ID/packer-images/windows-packer-builder:latest'

serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/your-sa-name@$PROJECT_ID.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
