#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Applies Windows Server 2025 OpenSSH STIG hardening.
    Covers V-285313 through V-285323.
    Installs OpenSSH if needed, configures sshd_config, sets file permissions.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'

function Write-OK    ($m) { Write-Host "  [OK]   $m" -ForegroundColor Green  }
function Write-Fixed ($m) { Write-Host "  [FIX]  $m" -ForegroundColor Yellow }
function Write-Warn  ($m) { Write-Host "  [WARN] $m" -ForegroundColor Magenta }
function Write-Section ($m) {
    Write-Host "`n========================================" -ForegroundColor Cyan
    Write-Host " $m" -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
}

$ErrorCount = 0

# -----------------------------------------------------------------------
# V-285313: OpenSSH must be installed and available
# -----------------------------------------------------------------------
Write-Section "V-285313: Ensure OpenSSH Server is installed"

$sshdFeature = Get-WindowsCapability -Online | Where-Object { $_.Name -like 'OpenSSH.Server*' }

if ($sshdFeature.State -ne 'Installed') {
    Write-Host "  Installing OpenSSH Server..."
    try {
        Add-WindowsCapability -Online -Name $sshdFeature.Name -ErrorAction Stop | Out-Null
        Write-Fixed "OpenSSH Server installed"
    } catch {
        Write-Warn "Failed to install OpenSSH Server: $_"
        $ErrorCount++
    }
} else {
    Write-OK "OpenSSH Server already installed"
}

# Ensure sshd service is set to Automatic (do NOT start during Packer build —
# starting sshd can return exit code 16001 which kills the Packer pipeline.
# The service will auto-start on first boot from the captured image.)
try {
    $svc = Get-Service -Name sshd -ErrorAction Stop
    Set-Service -Name sshd -StartupType Automatic -ErrorAction SilentlyContinue
    Write-OK "sshd service set to Automatic (will start on first boot)"
} catch {
    Write-Warn "sshd service configuration failed: $_"
    $ErrorCount++
}

# -----------------------------------------------------------------------
# Configure sshd_config
# -----------------------------------------------------------------------
Write-Section "Configuring sshd_config (V-285314 through V-285323)"

$sshdConfigPath = "$env:ProgramData\ssh\sshd_config"
$sshdConfigDir  = "$env:ProgramData\ssh"

if (!(Test-Path $sshdConfigDir)) {
    New-Item -Path $sshdConfigDir -ItemType Directory -Force | Out-Null
}

# Create DoD banner file for SSH
$bannerPath = "$sshdConfigDir\sshd_banner.txt"
$bannerText = @"
You are accessing a U.S. Government information system, which includes: 1) this computer, 2) this computer network, 3) all Government-furnished computers connected to this network, and 4) all Government-furnished devices and storage media attached to this network or to a computer on this network. You understand and consent to the following: you may access this information system for authorized use only; unauthorized use of the system is prohibited and subject to criminal and civil penalties. You have no reasonable expectation of privacy regarding any communication or data transiting or stored on this information system. At any time and for any lawful Government purpose, the Government may monitor, intercept, audit, and search and seize any communication or data transiting or stored on this information system, and any communication or data transiting or stored on this information system may be disclosed or used for any lawful Government purpose. This information system may contain Controlled Unclassified Information (CUI) that is subject to safeguarding or dissemination controls in accordance with law, regulation, or Government-wide policy. Accessing and using this system indicates your understanding of this warning.
"@
Set-Content -Path $bannerPath -Value $bannerText -Encoding UTF8 -Force
Write-Fixed "V-285314: SSH banner file created at $bannerPath"

# Build the hardened sshd_config
$sshdConfig = @"
# Windows Server 2025 STIG-hardened sshd_config
# Generated by openssh_stig.ps1

# V-285314: Display DoD banner before granting access
Banner $bannerPath

# V-285315: Accept public key authentication
PubkeyAuthentication yes

# V-285316 (CAT I): No blank/empty passwords
PermitEmptyPasswords no

# V-285317: Force frequent session key renegotiation
# RekeyLimit: renegotiate after 1GB data or 1 hour
RekeyLimit 1G 1h

# V-285318 / V-285319: Terminate idle/inactive connections
# ClientAliveInterval: send keepalive every 600 seconds (10 min)
# ClientAliveCountMax: disconnect after 1 missed keepalive
ClientAliveInterval 600
ClientAliveCountMax 1

# V-285320: Configuration file minimum requirements
# StrictModes ensures proper file permissions on user files
StrictModes yes

# V-285323: No GSSAPI authentication
GSSAPIAuthentication no

# Additional hardening
PasswordAuthentication yes
MaxAuthTries 3
MaxSessions 10
AllowTcpForwarding no
PermitRootLogin no
IgnoreRhosts yes
HostbasedAuthentication no
Ciphers aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512,hmac-sha2-256
KexAlgorithms ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512

# Host keys
HostKey C:\ProgramData\ssh\ssh_host_rsa_key
HostKey C:\ProgramData\ssh\ssh_host_ecdsa_key
HostKey C:\ProgramData\ssh\ssh_host_ed25519_key

# Logging
SyslogFacility LOCAL0
LogLevel INFO

# Subsystem
Subsystem sftp sftp-server.exe

# Admin authorized keys
Match Group administrators
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
"@

# Backup existing config
if (Test-Path $sshdConfigPath) {
    Copy-Item $sshdConfigPath "$sshdConfigPath.bak.$(Get-Date -Format 'yyyyMMdd-HHmmss')" -Force
    Write-OK "Backed up existing sshd_config"
}

Set-Content -Path $sshdConfigPath -Value $sshdConfig -Encoding UTF8 -Force
Write-Fixed "sshd_config written with STIG-hardened settings"

# -----------------------------------------------------------------------
# V-285321: Private host key files — restrict permissions
# V-285322: Public host key files — restrict permissions
# -----------------------------------------------------------------------
Write-Section "V-285321/V-285322: SSH host key file permissions"

# Generate host keys if they don't exist
$hostKeys = @(
    "$sshdConfigDir\ssh_host_rsa_key",
    "$sshdConfigDir\ssh_host_ecdsa_key",
    "$sshdConfigDir\ssh_host_ed25519_key"
)

foreach ($keyFile in $hostKeys) {
    if (!(Test-Path $keyFile)) {
        Write-Host "  Generating host key: $keyFile"
        $keyType = if ($keyFile -match 'rsa') { 'rsa' } elseif ($keyFile -match 'ecdsa') { 'ecdsa' } else { 'ed25519' }
        & ssh-keygen -t $keyType -f $keyFile -N '""' -q 2>&1 | Out-Null
    }
}

# Set permissions on private host key files (V-285321)
# Only SYSTEM and Administrators should have access
foreach ($keyFile in $hostKeys) {
    if (Test-Path $keyFile) {
        try {
            $acl = Get-Acl $keyFile
            $acl.SetAccessRuleProtection($true, $false)
            $acl.Access | ForEach-Object { $acl.RemoveAccessRule($_) | Out-Null }

            $systemRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
                "NT AUTHORITY\SYSTEM", "FullControl", "Allow")
            $adminRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
                "BUILTIN\Administrators", "FullControl", "Allow")

            $acl.AddAccessRule($systemRule)
            $acl.AddAccessRule($adminRule)
            Set-Acl -Path $keyFile -AclObject $acl
            Write-Fixed "V-285321: Restricted permissions on $keyFile"
        } catch {
            Write-Warn "Failed to set permissions on $keyFile : $_"
            $ErrorCount++
        }
    }
}

# Set permissions on public host key files (V-285322)
# ONLY SYSTEM + Administrators — SCC checks "Other accounts: none_exists"
foreach ($keyFile in $hostKeys) {
    $pubKey = "$keyFile.pub"
    if (Test-Path $pubKey) {
        try {
            $acl = Get-Acl $pubKey
            $acl.SetAccessRuleProtection($true, $false)
            $acl.Access | ForEach-Object { $acl.RemoveAccessRule($_) | Out-Null }

            $systemRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
                "NT AUTHORITY\SYSTEM", "FullControl", "Allow")
            $adminRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
                "BUILTIN\Administrators", "FullControl", "Allow")

            $acl.AddAccessRule($systemRule)
            $acl.AddAccessRule($adminRule)
            Set-Acl -Path $pubKey -AclObject $acl
            Write-Fixed "V-285322: Set permissions on $pubKey"
        } catch {
            Write-Warn "Failed to set permissions on $pubKey : $_"
            $ErrorCount++
        }
    }
}

# -----------------------------------------------------------------------
# V-285320: sshd_config file permissions
# -----------------------------------------------------------------------
Write-Section "V-285320: sshd_config file permissions"

try {
    $acl = Get-Acl $sshdConfigPath
    $acl.SetAccessRuleProtection($true, $false)
    $acl.Access | ForEach-Object { $acl.RemoveAccessRule($_) | Out-Null }

    $systemRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        "NT AUTHORITY\SYSTEM", "FullControl", "Allow")
    $adminRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        "BUILTIN\Administrators", "FullControl", "Allow")

    # SCC requires Authenticated Users:(RX) on sshd_config
    $rxRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        "NT AUTHORITY\Authenticated Users", "ReadAndExecute", "Allow")

    $acl.AddAccessRule($systemRule)
    $acl.AddAccessRule($adminRule)
    $acl.AddAccessRule($rxRule)
    Set-Acl -Path $sshdConfigPath -AclObject $acl
    Write-Fixed "sshd_config permissions: SYSTEM(F) + Admins(F) + AuthUsers(RX)"
} catch {
    Write-Warn "Failed to set sshd_config permissions: $_"
    $ErrorCount++
}

# -----------------------------------------------------------------------
# Stop sshd if running (do NOT restart — service will start on first boot)
# -----------------------------------------------------------------------
Write-Section "Finalizing sshd service"

try {
    Stop-Service sshd -Force -ErrorAction SilentlyContinue
    $svc = Get-Service sshd
    if ($svc.StartType -eq 'Automatic') {
        Write-OK "sshd service restarted and running"
    } else {
        Write-Warn "sshd StartType: $($svc.StartType) (expected Automatic)"
        $ErrorCount++
    }
} catch {
    Write-Warn "sshd finalization: $_"
}

# -----------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------
Write-Section "OpenSSH STIG Summary"

if ($ErrorCount -eq 0) {
    Write-Host "  All OpenSSH STIG fixes applied successfully." -ForegroundColor Green
} else {
    Write-Host "  $ErrorCount issue(s) need attention." -ForegroundColor Yellow
}

exit $ErrorCount
